In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("Dataset/50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [184]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,4].values

X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 294919.57, 'Florida'],
       [86419.7, 153514.11, 0.0, 'New York'],
       [76253.86, 113867.3, 298664.47, 'California'],
       [78389.47, 153773.43, 299737.29, 'New York'],
       [73994.56, 122782.75, 303319.26, 'Florida'],
       [67532.53, 105751.03, 304768.73, 'Florida'],
       [77044.01, 99281.34, 140574.81, 'New York'],
       [64664.71, 139553.16, 137962.62, 'California'],
       [75328.87, 144135.98, 134050.07, 'Florida'],
       [72107.6, 127864.55, 353183.81, 'New York'],
       [66051.52, 182645.56, 118148.2, 'Florida'],
       [65605.48, 153032.06, 107138.38, 'New York'],
       [61994.48, 115641.28, 91131.24, 'Florida'],
       [61136.38, 152701.92, 88218.23, 'New York'],
       [63408.86, 129219.61, 46085.25, 'California'],
       [55493.95, 103057.49, 214634.81, 'Florida'],
       [46426.07, 157693.92, 210797.67, 'California'],
       [46014.02, 85047.44, 205517.64, 'New York'],
       [28663.76, 127056.21, 201126.82, 'Florida'],
       [44069.95, 51283.14, 197029.42, 'California'],
       [20229.59, 65947.93, 185265.1, 'New York'],
       [38558.51, 82982.09, 174999.3, 'California'],
       [28754.33, 118546.05, 172795.67, 'California'],
       [27892.92, 84710.77, 164470.71, 'Florida'],
       [23640.93, 96189.63, 148001.11, 'California'],
       [15505.73, 127382.3, 35534.17, 'New York'],
       [22177.74, 154806.14, 28334.72, 'California'],
       [1000.23, 124153.04, 1903.93, 'New York'],
       [1315.46, 115816.21, 297114.46, 'Florida'],
       [0.0, 135426.92, 0.0, 'California'],
       [542.05, 51743.15, 0.0, 'New York'],
       [0.0, 116983.8, 45173.06, 'California']], dtype=object)

In [187]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [188]:
#Encoding the categorial data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[('cat', OneHotEncoder(), [3])], remainder = 'passthrough')
X = transformer.fit_transform(X)
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 0.0, 1.0, 86419.7, 153514.11, 0.0],
       [1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [0.0, 1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [0.0, 1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [0.0, 0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [1.0, 0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [0.0, 1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [1.0, 0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [1.0, 0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [1.0, 0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [0.0, 1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1.0, 0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [0.0, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [1.0, 0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [1.0, 0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

In [189]:
#Avoiding the Dummy Variable Trap
X = X[:,1:]  #start from index 1 to n and ignore 0 index
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7, 153514.11, 0.0],
       [0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

In [190]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=0)
X_train

array([[1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [0.0, 0.0, 0.0, 116983.8, 45173.06],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [0.0, 1.0, 86419.7, 153514.11, 0.0],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 0.0, 22177.74, 154806.14, 28334.72]], dtype=object)

In [191]:
X_test

array([[1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [192]:
Y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [193]:
Y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [196]:
#Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

#Predicting the test set results
y_pred = regressor.predict(X_test)
y_pred

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [197]:
#Building the optimal model using Backward Elimination
    #sm = stats model

#sm doesn't consider b0 constant
#so we have to add a column with value = 1, considering x0 = 1 so that sm will consider b0
#axis = 1 -> column
#X = np.append(arr = X, values = np.ones((50,1)).astype(int), axis = 1)  #here column ones is added to arr X at the end

X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)   #here array X is added to arr of ones
X

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [1, 0.0, 1.0, 86419.7, 153514.11, 0.0],
       [1, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [1, 0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [1, 1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1, 1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [1, 0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [1, 0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [1, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [1, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1, 1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [1, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [1, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [1, 0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [1, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [1, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1, 1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [1, 0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [1, 0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [1, 0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [1, 0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [1, 1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [1, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1, 0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [1, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [1, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [1, 0.0, 0.0, 0.0, 135426.92, 0.0],
       [1, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [1, 0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

In [212]:
#creating optimal matrix of features
#X_opt contains only independent variables that are highly statistically significant for calulating dependent variable
import statsmodels.formula.api as sm 

X_opt = X[:,[0,1,2,3,4,5]] 

#ols = ordinary least square
regressor_OLS =  sm.ols(endog = Y, exog = X_opt, data = dataset, formula = 'R&D Spend + Administration + Marketing Spend + State').fit()

#contain information about multilinear regression model
regressor_OLS.summary()

SyntaxError: invalid syntax (<unknown>, line 1)

In [203]:
X_opt = X[:,[0,1,3,4,5]]  # 2 has highest P value so removing it
regressor_OLS = sm.OLS(Y, X_opt).fit()
regressor_OLS.summary()

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [117]:
X_opt = X[:,[0,3,4,5]]  
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [ ]:
X_opt = X[:,[0,3,5]]  
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

In [ ]:
X_opt = X[:,[0,3]]  
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()